// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/watch-variants/BroadcastGrid.tsx": () => import("../components/mockups/watch-variants/BroadcastGrid.tsx"),
  "./components/mockups/watch-variants/CommandDashboard.tsx": () => import("../components/mockups/watch-variants/CommandDashboard.tsx"),
  "./components/mockups/watch-variants/SportSignal.tsx": () => import("../components/mockups/watch-variants/SportSignal.tsx"),
  "./components/mockups/watch-variants/TonightsLineCard.tsx": () => import("../components/mockups/watch-variants/TonightsLineCard.tsx"),
  "./components/mockups/ritual-cards/CompactRow.tsx": () => import("../components/mockups/ritual-cards/CompactRow.tsx"),
  "./components/mockups/ritual-cards/HeroGradient.tsx": () => import("../components/mockups/ritual-cards/HeroGradient.tsx"),
  "./components/mockups/ritual-cards/SportPalette.tsx": () => import("../components/mockups/ritual-cards/SportPalette.tsx"),
  "./components/mockups/daily-wrap-variants/SportSections.tsx": () => import("../components/mockups/daily-wrap-variants/SportSections.tsx"),
  "./components/mockups/daily-wrap-variants/Ticker.tsx": () => import("../components/mockups/daily-wrap-variants/Ticker.tsx"),
  "./components/mockups/daily-wrap-variants/TopStory.tsx": () => import("../components/mockups/daily-wrap-variants/TopStory.tsx"),
  "./components/mockups/daily-wrap-variants/YourTeams.tsx": () => import("../components/mockups/daily-wrap-variants/YourTeams.tsx")
};
