const JL_SHORT_NAMES: Record<string, string> = {
  "Brave Lupus Tokyo": "Brave Lupus",
  "Black Rams Tokyo": "Black Rams",
  "Kobelco Kobe Steelers": "Steelers",
  "Saitama Wild Knights": "Wild Knights",
  "Tokyo-Bay Urayasu D-Rocks": "D-Rocks",
  "Urayasu D-Rocks": "D-Rocks",
  "Toyota Verblitz": "Verblitz",
  "Mie Honda Heat": "Heat",
  "Tokyo Sungoliath": "Sungoliath",
  "Yokohama Canon Eagles": "Canon Eagles",
  "Sagamihara Dynaboars": "Dynaboars",
  "Shizuoka Blue Revs": "Blue Revs",
};

const SHORT_NAMES: Record<string, string> = {
  "Pittsburgh Penguins": "Penguins",
  "New York Rangers": "Rangers",
  "New York Islanders": "Islanders",
  "New Jersey Devils": "Devils",
  "Philadelphia Flyers": "Flyers",
  "Washington Capitals": "Capitals",
  "Carolina Hurricanes": "Hurricanes",
  "Columbus Blue Jackets": "Blue Jackets",
  "Tampa Bay Lightning": "Lightning",
  "Florida Panthers": "Panthers",
  "Toronto Maple Leafs": "Maple Leafs",
  "Montréal Canadiens": "Canadiens",
  "Detroit Red Wings": "Red Wings",
  "Chicago Blackhawks": "Blackhawks",
  "Nashville Predators": "Predators",
  "Colorado Avalanche": "Avalanche",
  "Vegas Golden Knights": "Golden Knights",
  "Los Angeles Kings": "Kings",
  "Vancouver Canucks": "Canucks",
  "Edmonton Oilers": "Oilers",
  "San Jose Sharks": "Sharks",
  "Ottawa Senators": "Senators",
  "St. Louis Blues": "Blues",
  "Minnesota Wild": "Wild",
  "Winnipeg Jets": "Jets",
  "Calgary Flames": "Flames",
  "Dallas Stars": "Stars",
  "Seattle Kraken": "Kraken",
  "Anaheim Ducks": "Ducks",
  "Buffalo Sabres": "Sabres",
  "Boston Bruins": "Bruins",
  "Utah Hockey Club": "Utah HC",

  "Wilkes-Barre/Scranton Penguins": "WBS Penguins",
  "Coachella Valley Firebirds": "CV Firebirds",
  "Springfield Thunderbirds": "Thunderbirds",
  "Henderson Silver Knights": "Silver Knights",
  "Greenville Swamp Rabbits": "Swamp Rabbits",
  "Lehigh Valley Phantoms": "Phantoms",
  "Grand Rapids Griffins": "Griffins",
  "Kansas City Mavericks": "Mavericks",
  "Bridgeport Islanders": "Islanders",
  "Rochester Americans": "Americans",
  "Belleville Senators": "Senators",
  "Bakersfield Condors": "Condors",
  "Charlotte Checkers": "Checkers",
  "Hartford Wolf Pack": "Wolf Pack",
  "Cleveland Monsters": "Monsters",
  "Milwaukee Admirals": "Admirals",
  "San Jose Barracuda": "Barracuda",
  "Abbotsford Canucks": "Canucks",
  "Tucson Roadrunners": "Roadrunners",
  "Calgary Wranglers": "Wranglers",
  "Providence Bruins": "Bruins",
  "Colorado Eagles": "Eagles",
  "Allen Americans": "Americans",
  "San Diego Gulls": "Gulls",
  "Toronto Marlies": "Marlies",
  "Syracuse Crunch": "Crunch",
  "Rockford IceHogs": "IceHogs",
  "Rapid City Rush": "Rush",
  "Iowa Heartlanders": "Heartlanders",

  "FC Bayern München": "Bayern",
  "Borussia Dortmund": "Dortmund",
  "Bayer 04 Leverkusen": "Leverkusen",
  "Eintracht Frankfurt": "Frankfurt",
  "Borussia Mönchengladbach": "Gladbach",
  "Sport-Club Freiburg": "Freiburg",
  "1. FC Heidenheim 1846": "Heidenheim",
  "1. FC Union Berlin": "Union Berlin",
  "SV Werder Bremen": "Werder Bremen",
  "1. FSV Mainz 05": "Mainz",
  "FC St. Pauli": "St. Pauli",
  "RB Leipzig": "Leipzig",
  "VfB Stuttgart": "Stuttgart",
  "VfL Wolfsburg": "Wolfsburg",
  "TSG Hoffenheim": "Hoffenheim",
  "FC Augsburg": "Augsburg",
  "Holstein Kiel": "Holstein Kiel",
  "1. FC Köln": "Köln",

  "Wolverhampton Wanderers": "Wolves",
  "Brighton & Hove Albion": "Brighton",
  "Birmingham City": "Birmingham",
  "Macclesfield FC": "Macclesfield",

  "Olympique de Marseille": "Marseille",
  "Olympique Lyonnais": "Lyon",
  "Paris Saint-Germain": "PSG",
  "RC Strasbourg Alsace": "Strasbourg",
  "Stade Brestois 29": "Brest",
  "Stade Rennais FC": "Rennes",
  "Havre Athletic Club": "Le Havre",
  "AS Saint-Étienne": "St-Étienne",
  "Montpellier HSC": "Montpellier",

  "Atlético de Madrid": "Atlético",
  "RCD Espanyol de Barcelona": "Espanyol",
  "Deportivo Alavés": "Alavés",
  "Athletic Club": "Athletic",
  "Real Sociedad": "Real Sociedad",
  "Real Betis": "Betis",
  "Celta de Vigo": "Celta Vigo",

  "Boston University": "BU",

  "New York City Football Club": "NYCFC",
  "Los Angeles Football Club": "LAFC",
  "New England Revolution": "Revolution",
  "Vancouver Whitecaps FC": "Whitecaps",
  "Sporting Kansas City": "Sporting KC",
  "San Jose Earthquakes": "Earthquakes",
  "Minnesota United FC": "Minnesota Utd",
  "Seattle Sounders FC": "Sounders",
  "Philadelphia Union": "Union",
  "Houston Dynamo FC": "Dynamo",
  "St. Louis CITY SC": "St. Louis",
  "Red Bull New York": "NY Red Bulls",
  "Louisville City FC": "Louisville",
  "Colorado Rapids": "Rapids",
  "Chicago Fire FC": "Chicago Fire",
  "Portland Timbers": "Timbers",

  "Queensland Reds": "Reds",
};

const COMPACT_NAMES: Record<string, string> = {
  "Las Vegas Lights FC": "LV Lights",
  "Orange County SC": "OC SC",
  "Colorado Springs Switchbacks FC": "CO Springs",
  "El Paso Locomotive FC": "El Paso",
  "Birmingham Legion FC": "Birmingham",
  "Louisville City FC": "Louisville",
  "Sacramento Republic FC": "Sacramento",
  "Phoenix Rising FC": "Phoenix",
  "Pittsburgh Riverhounds": "Pittsburgh",
  "Tampa Bay Rowdies": "TB Rowdies",
  "San Antonio FC": "San Antonio",
  "Rhode Island FC": "Rhode Island",
  "Charleston Battery": "Charleston",
  "Hartford Athletic": "Hartford",
  "Detroit City FC": "Detroit City",
  "Loudoun United FC": "Loudoun Utd",
  "New Mexico United": "NM United",
  "Monterey Bay": "Monterey Bay",
  "Oakland Roots": "Oakland",
  "FC Tulsa": "Tulsa",
  "Brooklyn FC": "Brooklyn",
  "Sporting JAX": "JAX",
  "Miami FC": "Miami",
  "Indy Eleven": "Indy",
  "New York City Football Club": "NYCFC",
  "Los Angeles Football Club": "LAFC",
  "New England Revolution": "Revolution",
  "Sporting Kansas City": "Sporting KC",
  "San Jose Earthquakes": "Earthquakes",
  "Minnesota United FC": "Minnesota",
  "Seattle Sounders FC": "Sounders",
  "Philadelphia Union": "Union",
  "Houston Dynamo FC": "Dynamo",
  "St. Louis CITY SC": "St. Louis",
  "Red Bull New York": "NY Red Bulls",
  "Chicago Fire FC": "Chicago Fire",
  "Portland Timbers": "Timbers",
  "Colorado Rapids": "Rapids",
  "Vancouver Whitecaps FC": "Whitecaps",
  "San Diego FC": "San Diego",
  "FC Bayern München": "Bayern",
  "Borussia Dortmund": "Dortmund",
  "Bayer 04 Leverkusen": "Leverkusen",
  "Eintracht Frankfurt": "Frankfurt",
  "Borussia Mönchengladbach": "Gladbach",
  "Wolverhampton Wanderers": "Wolves",
  "Brighton & Hove Albion": "Brighton",
  "Paris Saint-Germain": "PSG",
  "Atlético de Madrid": "Atlético",
  "Coachella Valley Firebirds": "CV Firebirds",
  "Wilkes-Barre/Scranton Penguins": "WBS Penguins",
  "Springfield Thunderbirds": "T-birds",
  "Henderson Silver Knights": "Silver Knights",
  "Greenville Swamp Rabbits": "Swamp Rabbits",
  "San Diego Gulls": "Gulls",
  "Anaheim Ducks": "Ducks",
  "Boston University": "BU",
};

export function displayTeamName(team: string, league?: string): string {
  if (league === "Japan League One") {
    return JL_SHORT_NAMES[team] || team;
  }
  return SHORT_NAMES[team] || team;
}

export function compactTeamName(team: string, league?: string): string {
  if (league === "Japan League One") {
    return JL_SHORT_NAMES[team] || team;
  }
  if (COMPACT_NAMES[team]) return COMPACT_NAMES[team];
  if (SHORT_NAMES[team]) return SHORT_NAMES[team];
  return team;
}
