const JL_SHORT_NAMES: Record<string, string> = {
  "Brave Lupus Tokyo": "Brave Lupus",
  "Black Rams Tokyo": "Black Rams",
  "Kobelco Kobe Steelers": "Steelers",
  "Saitama Wild Knights": "Wild Knights",
  "Tokyo-Bay Urayasu D-Rocks": "D-Rocks",
  "Urayasu D-Rocks": "D-Rocks",
  "Toyota Verblitz": "Verblitz",
  "Mie Honda Heat": "Heat",
  "Tokyo Sungoliath": "Sungoliath",
  "Yokohama Canon Eagles": "Canon Eagles",
  "Sagamihara Dynaboars": "Dynaboars",
  "Shizuoka Blue Revs": "Blue Revs",
};

const SHORT_NAMES: Record<string, string> = {
  "Pittsburgh Penguins": "Penguins",
  "New York Rangers": "Rangers",
  "New York Islanders": "Islanders",
  "New Jersey Devils": "Devils",
  "Philadelphia Flyers": "Flyers",
  "Washington Capitals": "Capitals",
  "Carolina Hurricanes": "Hurricanes",
  "Columbus Blue Jackets": "Blue Jackets",
  "Tampa Bay Lightning": "Lightning",
  "Florida Panthers": "Panthers",
  "Toronto Maple Leafs": "Maple Leafs",
  "Montréal Canadiens": "Canadiens",
  "Detroit Red Wings": "Red Wings",
  "Chicago Blackhawks": "Blackhawks",
  "Nashville Predators": "Predators",
  "Colorado Avalanche": "Avalanche",
  "Vegas Golden Knights": "Golden Knights",
  "Los Angeles Kings": "Kings",
  "Vancouver Canucks": "Canucks",
  "Edmonton Oilers": "Oilers",
  "San Jose Sharks": "Sharks",
  "Ottawa Senators": "Senators",
  "St. Louis Blues": "Blues",
  "Minnesota Wild": "Wild",
  "Winnipeg Jets": "Jets",
  "Calgary Flames": "Flames",
  "Dallas Stars": "Stars",
  "Seattle Kraken": "Kraken",
  "Anaheim Ducks": "Ducks",
  "Buffalo Sabres": "Sabres",
  "Boston Bruins": "Bruins",
  "Utah Hockey Club": "Utah HC",

  "Atlanta Hawks": "Hawks",
  "UC Irvine Anteaters": "Anteaters",
  "UC Davis Aggies": "UC Davis",
  "UC Santa Barbara Gauchos": "UCSB",
  "UC San Diego Tritons": "UC San Diego",
  "UC Riverside Highlanders": "UC Riverside",
  "Cal Poly Mustangs": "Cal Poly",
  "Hawai'i Rainbow Warriors": "Hawai'i",
  "Long Beach State Beach": "Long Beach",
  "Cal State Fullerton Titans": "CS Fullerton",
  "Cal State Northridge Matadors": "CS Northridge",
  "Cal State Bakersfield Roadrunners": "CS Bakersfield",
  "Boston Celtics": "Celtics",
  "Brooklyn Nets": "Nets",
  "Charlotte Hornets": "Hornets",
  "Chicago Bulls": "Bulls",
  "Cleveland Cavaliers": "Cavaliers",
  "Dallas Mavericks": "Mavericks",
  "Denver Nuggets": "Nuggets",
  "Detroit Pistons": "Pistons",
  "Golden State Warriors": "Warriors",
  "Houston Rockets": "Rockets",
  "Indiana Pacers": "Pacers",
  "LA Clippers": "Clippers",
  "Los Angeles Lakers": "Lakers",
  "Memphis Grizzlies": "Grizzlies",
  "Miami Heat": "Heat",
  "Milwaukee Bucks": "Bucks",
  "Minnesota Timberwolves": "Timberwolves",
  "New Orleans Pelicans": "Pelicans",
  "New York Knicks": "Knicks",
  "Oklahoma City Thunder": "Thunder",
  "Orlando Magic": "Magic",
  "Philadelphia 76ers": "76ers",
  "Phoenix Suns": "Suns",
  "Portland Trail Blazers": "Trail Blazers",
  "Sacramento Kings": "Kings",
  "San Antonio Spurs": "Spurs",
  "Toronto Raptors": "Raptors",
  "Utah Jazz": "Jazz",
  "Washington Wizards": "Wizards",

  "Wilkes-Barre/Scranton Penguins": "WBS Penguins",
  "Coachella Valley Firebirds": "CV Firebirds",
  "Springfield Thunderbirds": "Thunderbirds",
  "Henderson Silver Knights": "Silver Knights",
  "Greenville Swamp Rabbits": "Swamp Rabbits",
  "Lehigh Valley Phantoms": "Phantoms",
  "Grand Rapids Griffins": "Griffins",
  "Kansas City Mavericks": "Mavericks",
  "Bridgeport Islanders": "Islanders",
  "Rochester Americans": "Americans",
  "Belleville Senators": "Senators",
  "Bakersfield Condors": "Condors",
  "Charlotte Checkers": "Checkers",
  "Hartford Wolf Pack": "Wolf Pack",
  "Cleveland Monsters": "Monsters",
  "Milwaukee Admirals": "Admirals",
  "San Jose Barracuda": "Barracuda",
  "Abbotsford Canucks": "Canucks",
  "Tucson Roadrunners": "Roadrunners",
  "Calgary Wranglers": "Wranglers",
  "Providence Bruins": "Bruins",
  "Colorado Eagles": "Eagles",
  "Allen Americans": "Americans",
  "San Diego Gulls": "Gulls",
  "Toronto Marlies": "Marlies",
  "Syracuse Crunch": "Crunch",
  "Rockford IceHogs": "IceHogs",
  "Rapid City Rush": "Rush",
  "Iowa Heartlanders": "Heartlanders",

  "FC Bayern München": "Bayern",
  "Borussia Dortmund": "Dortmund",
  "Bayer 04 Leverkusen": "Leverkusen",
  "Eintracht Frankfurt": "Frankfurt",
  "Borussia Mönchengladbach": "Gladbach",
  "Sport-Club Freiburg": "Freiburg",
  "1. FC Heidenheim 1846": "Heidenheim",
  "1. FC Union Berlin": "Union Berlin",
  "SV Werder Bremen": "Werder Bremen",
  "1. FSV Mainz 05": "Mainz",
  "FC St. Pauli": "St. Pauli",
  "RB Leipzig": "Leipzig",
  "VfB Stuttgart": "Stuttgart",
  "VfL Wolfsburg": "Wolfsburg",
  "TSG Hoffenheim": "Hoffenheim",
  "FC Augsburg": "Augsburg",
  "Holstein Kiel": "Holstein Kiel",
  "1. FC Köln": "Köln",

  "Wolverhampton Wanderers": "Wolves",
  "Brighton & Hove Albion": "Brighton",
  "Birmingham City": "Birmingham",
  "Macclesfield FC": "Macclesfield",

  "Olympique de Marseille": "Marseille",
  "Olympique Lyonnais": "Lyon",
  "Paris Saint-Germain": "PSG",
  "RC Strasbourg Alsace": "Strasbourg",
  "Stade Brestois 29": "Brest",
  "Stade Rennais FC": "Rennes",
  "Havre Athletic Club": "Le Havre",
  "AS Saint-Étienne": "St-Étienne",
  "Montpellier HSC": "Montpellier",

  "Atlético de Madrid": "Atlético",
  "RCD Espanyol de Barcelona": "Espanyol",
  "Deportivo Alavés": "Alavés",
  "Athletic Club": "Athletic",
  "Real Sociedad": "Real Sociedad",
  "Real Betis": "Betis",
  "Celta de Vigo": "Celta Vigo",

  "Boston University": "BU",

  "New York City Football Club": "NYCFC",
  "Los Angeles Football Club": "LAFC",
  "New England Revolution": "Revolution",
  "Vancouver Whitecaps FC": "Whitecaps",
  "Sporting Kansas City": "Sporting KC",
  "San Jose Earthquakes": "Earthquakes",
  "Minnesota United FC": "Minnesota Utd",
  "Seattle Sounders FC": "Sounders",
  "Philadelphia Union": "Union",
  "Houston Dynamo FC": "Dynamo",
  "St. Louis CITY SC": "St. Louis",
  "Red Bull New York": "NY Red Bulls",
  "Louisville City FC": "Louisville",
  "Colorado Rapids": "Rapids",
  "Chicago Fire FC": "Chicago Fire",
  "Portland Timbers": "Timbers",

  "Colorado Springs Switchbacks FC": "CO Switchbacks",
  "El Paso Locomotive FC": "El Paso Loco",
  "Las Vegas Lights FC": "LV Lights",
  "Orange County SC": "Orange County",
  "Birmingham Legion FC": "Birmingham",
  "Sacramento Republic FC": "Sacramento",
  "Phoenix Rising FC": "Phoenix Rising",
  "Pittsburgh Riverhounds": "Riverhounds",
  "Tampa Bay Rowdies": "TB Rowdies",
  "San Antonio FC": "San Antonio",
  "Rhode Island FC": "Rhode Island",
  "Charleston Battery": "Charleston",
  "Hartford Athletic": "Hartford",
  "Detroit City FC": "Detroit City",
  "Loudoun United FC": "Loudoun Utd",
  "New Mexico United": "NM United",
  "Oakland Roots": "Oakland Roots",
  "FC Tulsa": "Tulsa",
  "Brooklyn FC": "Brooklyn",
  "Sporting JAX": "Sporting JAX",
  "Miami FC": "Miami FC",
  "Indy Eleven": "Indy Eleven",

  "Queensland Reds": "Reds",

  // Super Rugby Pacific (additional)
  "ACT Brumbies": "Brumbies",
  "Fijian Drua": "Drua",
  "Moana Pasifika": "Pasifika",
  "Western Force": "Force",
  "Bulls Super": "Bulls",

  // English Premiership Rugby
  "Exeter Chiefs": "Exeter",
  "Northampton Saints": "Northampton",
  "Sale Sharks": "Sale",
  "Newcastle Falcons": "Newcastle",
  "Bath Rugby": "Bath",
  "Bristol Bears": "Bristol",
  "Saracens": "Saracens",
  "Harlequins": "Quins",

  // Top 14
  "Stade Français": "Stade Fr.",
  "La Rochelle": "La Rochelle",
  "Stade Rochelais": "La Rochelle",

  // MLR
  "New England Free Jacks": "Free Jacks",
  "Old Glory DC": "Old Glory",
  "San Diego Legion": "Legion",
  "Houston SaberCats": "SaberCats",
  "Seattle Seawolves": "Seawolves",
  "New York RFC": "NY RFC",
  "Chicago Hounds": "Hounds",
  "Utah Warriors": "Warriors",
  "RFC Los Angeles": "RFC LA",
  "Anthem RC": "Anthem RC",

  // AHL (additional)
  "Hershey Bears": "Bears",
  "Ontario Reign": "Reign",
  "Utica Comets": "Comets",
  "Chicago Wolves": "Wolves",
  "Manitoba Moose": "Moose",
  "Laval Rocket": "Laval",
  "Binghamton Devils": "Binghamton",
  "Texas Stars": "Texas",
  "Stockton Heat": "Stockton",
  "Iowa Wild": "Iowa Wild",

  // ECHL
  "Idaho Steelheads": "Steelheads",
  "Tulsa Oilers": "Oilers",
  "Utah Grizzlies": "Grizzlies",
  "Florida Everblades": "Everblades",
  "Maine Mariners": "Mariners",
  "Newfoundland Growlers": "Growlers",
  "Norfolk Admirals": "Admirals",
  "Reading Royals": "Royals",
  "Worcester Railers": "Railers",
  "Kalamazoo Wings": "K-Wings",
  "Fort Wayne Komets": "Komets",
  "Cincinnati Cyclones": "Cyclones",
  "Toledo Walleye": "Walleye",
  "Wheeling Nailers": "Nailers",
  "South Carolina Stingrays": "Stingrays",
  "Jacksonville Icemen": "Icemen",
  "Orlando Solar Bears": "Solar Bears",
  "Trois-Rivières Lions": "TR Lions",
  "Adirondack Thunder": "Adirondack",
  "Savannah Ghost Pirates": "Savannah",

  // MLS (additional)
  "Nashville SC": "Nashville",
  "Charlotte FC": "Charlotte",
  "Austin FC": "Austin",
  "CF Montréal": "Montréal",
  "D.C. United": "DC United",
  "Inter Miami": "Inter Miami",
  "LA Galaxy": "Galaxy",
  "Orlando City": "Orlando",
  "Columbus Crew": "Crew",
  "FC Dallas": "Dallas",
  "FC Cincinnati": "Cincinnati",
  "Toronto FC": "Toronto FC",
  "Atlanta United": "Atlanta Utd",
  "Real Salt Lake": "Real SL",
  "Angel City": "Angel City",
  "San Diego FC": "San Diego",

  // NWSL
  "Chicago Stars": "Stars",
  "Washington Spirit": "Spirit",
  "Houston Dash": "Dash",
  "Utah Royals": "Royals",
  "Denver Summit": "Summit",
  "Gotham FC": "Gotham",
  "Boston Legacy": "Legacy",
  "Racing Louisville": "Louisville",
  "North Carolina Courage": "NC Courage",
  "Portland Thorns": "Thorns",
  "Seattle Reign": "Reign",
  "Kansas City Current": "KC Current",
  "San Diego Wave": "San Diego",

  // European Soccer (CL/UEL teams using API spellings)
  "AS Roma": "Roma",
  "AS Monaco": "Monaco",
  "AJ Auxerre": "Auxerre",
  "Bayer Leverkusen": "Leverkusen",
  "Bodo/Glimt": "Glimt",
  "FC Porto": "Porto",
  "FC Cologne": "Cologne",
  "FC Midtjylland": "Midtjylland",
  "Galatasaray": "Galatasaray",
  "Hamburg SV": "Hamburg",
  "Hellas Verona": "Verona",
  "Racing Genk": "Genk",
  "Real Valladolid": "Valladolid",
  "Red Star Belgrade": "Red Star",
  "SC Freiburg": "Freiburg",
  "Slavia Prague": "Slavia",
  "Sporting CP": "Sporting",
  "Werder Bremen": "Werder",
  "Ferencvaros": "Ferencvaros",
  "Fenerbahce": "Fenerbahce",
  "Besiktas": "Besiktas",
  "Club Brugge": "Brugge",
  "Dinamo Zagreb": "Dinamo",
  "Feyenoord": "Feyenoord",
  "RB Salzburg": "Salzburg",
  "Red Bull Salzburg": "Salzburg",
  "Shakhtar Donetsk": "Shakhtar",
  "PSV Eindhoven": "PSV",
  "Ajax Amsterdam": "Ajax",
  "Benfica": "Benfica",
  "Sporting Lisbon": "Sporting",
  "Celtic FC": "Celtic",
  "Rangers FC": "Rangers",
  "Olympique Marseille": "Marseille",
  "Olympiacos": "Olympiacos",
  "Panathinaikos": "Panathinaikos",
  "PAOK": "PAOK",
  "Villarreal CF": "Villarreal",
  "Sevilla FC": "Sevilla",
  "Real Betis Balompié": "Betis",
  "West Ham United": "West Ham",
  "Nottingham Forest": "Nott'm Forest",
  "Nottm Forest": "Nott'm Forest",
  "Sheffield United": "Sheffield Utd",
  "Leicester City": "Leicester",
  "Tottenham Hotspur": "Spurs",
  "Manchester City": "Man City",
  "Manchester United": "Man Utd",
  "Newcastle United": "Newcastle",
  "Bayern Munich": "Bayern",
  "FC Bayern Munich": "Bayern",

  // Serie A
  "AC Milan": "AC Milan",
  "Inter Milan": "Inter",
  "Internazionale": "Inter",
  "Juventus FC": "Juventus",
  "SS Lazio": "Lazio",
  "SSC Napoli": "Napoli",
  "Fiorentina": "Fiorentina",
  "Atalanta BC": "Atalanta",
  "Hellas Verona FC": "Verona",
  "Udinese Calcio": "Udinese",
  "Cagliari Calcio": "Cagliari",
  "Bologna FC": "Bologna",
  "Genoa CFC": "Genoa",
  "Torino FC": "Torino",
  "Parma Calcio": "Parma",
  "Como 1907": "Como",
  "Venezia FC": "Venezia",
  "Empoli FC": "Empoli",
  "Monza": "Monza",
};

const COMPACT_NAMES: Record<string, string> = {
  "Las Vegas Lights FC": "LV Lights",
  "Orange County SC": "OC SC",
  "Colorado Springs Switchbacks FC": "CO Springs",
  "El Paso Locomotive FC": "El Paso",
  "Birmingham Legion FC": "Birmingham",
  "Louisville City FC": "Louisville",
  "Sacramento Republic FC": "Sacramento",
  "Phoenix Rising FC": "Phoenix",
  "Pittsburgh Riverhounds": "Pittsburgh",
  "Tampa Bay Rowdies": "TB Rowdies",
  "San Antonio FC": "San Antonio",
  "Rhode Island FC": "Rhode Island",
  "Charleston Battery": "Charleston",
  "Hartford Athletic": "Hartford",
  "Detroit City FC": "Detroit City",
  "Loudoun United FC": "Loudoun Utd",
  "New Mexico United": "NM United",
  "Monterey Bay": "Monterey Bay",
  "Oakland Roots": "Oakland",
  "FC Tulsa": "Tulsa",
  "Brooklyn FC": "Brooklyn",
  "Sporting JAX": "JAX",
  "Miami FC": "Miami",
  "Indy Eleven": "Indy",
  "New York City Football Club": "NYCFC",
  "Los Angeles Football Club": "LAFC",
  "New England Revolution": "Revolution",
  "Sporting Kansas City": "Sporting KC",
  "San Jose Earthquakes": "Earthquakes",
  "Minnesota United FC": "Minnesota",
  "Seattle Sounders FC": "Sounders",
  "Philadelphia Union": "Union",
  "Houston Dynamo FC": "Dynamo",
  "St. Louis CITY SC": "St. Louis",
  "Red Bull New York": "NY Red Bulls",
  "Chicago Fire FC": "Chicago Fire",
  "Portland Timbers": "Timbers",
  "Colorado Rapids": "Rapids",
  "Vancouver Whitecaps FC": "Whitecaps",
  "San Diego FC": "San Diego",
  "FC Bayern München": "Bayern",
  "Borussia Dortmund": "Dortmund",
  "Bayer 04 Leverkusen": "Leverkusen",
  "Eintracht Frankfurt": "Frankfurt",
  "Borussia Mönchengladbach": "Gladbach",
  "Wolverhampton Wanderers": "Wolves",
  "Brighton & Hove Albion": "Brighton",
  "Paris Saint-Germain": "PSG",
  "Atlético de Madrid": "Atlético",
  "Coachella Valley Firebirds": "CV Firebirds",
  "Wilkes-Barre/Scranton Penguins": "WBS Penguins",
  "Springfield Thunderbirds": "T-birds",
  "Henderson Silver Knights": "Silver Knights",
  "Greenville Swamp Rabbits": "Swamp Rabbits",
  "San Diego Gulls": "Gulls",
  "Anaheim Ducks": "Ducks",
  "Boston University": "BU",
  "Utah Mammoth": "Mammoth",
  "Utah Hockey Club": "Utah HC",
  "Newcastle United": "Newcastle",
  "Bayern Munich": "Bayern",
  "FC Bayern Munich": "Bayern",
  "Real Madrid": "Real Madrid",
  "Atlético Madrid": "Atlético",
  "Manchester City": "Man City",
  "Manchester United": "Man Utd",
  "Tottenham Hotspur": "Spurs",
  "West Ham United": "West Ham",
  "Nottm Forest": "Nott'm Forest",
  "Nottingham Forest": "Nott'm Forest",
  "Leicester City": "Leicester",
  "Sheffield United": "Sheffield Utd",
  "Crystal Palace": "Crystal Palace",
  "Aston Villa": "Aston Villa",
  "AC Milan": "AC Milan",
  "Inter Milan": "Inter",
  "Internazionale": "Inter",

  // Rugby
  "ACT Brumbies": "Brumbies",
  "Fijian Drua": "Drua",
  "Moana Pasifika": "Pasifika",
  "Western Force": "Force",
  "Bulls Super": "Bulls",
  "Exeter Chiefs": "Exeter",
  "Northampton Saints": "Northampton",
  "Sale Sharks": "Sale",
  "Newcastle Falcons": "Newcastle",
  "Bath Rugby": "Bath",
  "Bristol Bears": "Bristol",
  "Harlequins": "Quins",
  "Stade Français": "Stade Fr.",
  "Stade Rochelais": "La Rochelle",
  "New England Free Jacks": "Free Jacks",
  "Old Glory DC": "Old Glory",
  "San Diego Legion": "Legion",
  "Houston SaberCats": "SaberCats",
  "Seattle Seawolves": "Seawolves",
  "New York RFC": "NY RFC",
  "Chicago Hounds": "Hounds",
  "Utah Warriors": "Warriors",
  "RFC Los Angeles": "RFC LA",

  // AHL/ECHL
  "Hershey Bears": "Bears",
  "Ontario Reign": "Reign",
  "Utica Comets": "Comets",
  "Chicago Wolves": "Wolves",
  "Manitoba Moose": "Moose",
  "Idaho Steelheads": "Steelheads",
  "Tulsa Oilers": "Oilers",
  "Utah Grizzlies": "Grizzlies",
  "Florida Everblades": "Everblades",
  "Maine Mariners": "Mariners",
  "Newfoundland Growlers": "Growlers",
  "Savannah Ghost Pirates": "Savannah",
  "South Carolina Stingrays": "Stingrays",
  "Jacksonville Icemen": "Icemen",
  "Orlando Solar Bears": "Solar Bears",
  "Kalamazoo Wings": "K-Wings",
  "Fort Wayne Komets": "Komets",
  "Trois-Rivières Lions": "TR Lions",

  // MLS (additional)
  "Nashville SC": "Nashville",
  "Charlotte FC": "Charlotte",
  "Austin FC": "Austin",
  "CF Montréal": "Montréal",
  "D.C. United": "DC United",
  "Inter Miami": "Miami",
  "LA Galaxy": "Galaxy",
  "Orlando City": "Orlando",
  "Columbus Crew": "Crew",
  "FC Dallas": "Dallas",
  "FC Cincinnati": "Cincinnati",
  "Toronto FC": "Toronto FC",
  "Atlanta United": "Atlanta",
  "Real Salt Lake": "RSL",
  "Angel City": "Angel City",

  // NWSL
  "Chicago Stars": "Stars",
  "Washington Spirit": "Spirit",
  "Houston Dash": "Dash",
  "Utah Royals": "Royals",
  "Denver Summit": "Summit",
  "Gotham FC": "Gotham",
  "Boston Legacy": "Legacy",
  "North Carolina Courage": "NC Courage",
  "Kansas City Current": "KC Current",

  // European Soccer
  "AS Roma": "Roma",
  "AS Monaco": "Monaco",
  "AJ Auxerre": "Auxerre",
  "Bayer Leverkusen": "Leverkusen",
  "Bodo/Glimt": "Glimt",
  "FC Porto": "Porto",
  "FC Cologne": "Cologne",
  "FC Midtjylland": "Midtjylland",
  "Galatasaray": "Galatasaray",
  "Hamburg SV": "Hamburg",
  "Hellas Verona": "Verona",
  "Racing Genk": "Genk",
  "Real Valladolid": "Valladolid",
  "Red Star Belgrade": "Red Star",
  "SC Freiburg": "Freiburg",
  "Slavia Prague": "Slavia",
  "Sporting CP": "Sporting",
  "Werder Bremen": "Werder",
  "Club Brugge": "Brugge",
  "Dinamo Zagreb": "Dinamo",
  "RB Salzburg": "Salzburg",
  "Red Bull Salzburg": "Salzburg",
  "PSV Eindhoven": "PSV",
  "Celtic FC": "Celtic",
  "Rangers FC": "Rangers",
  "Shakhtar Donetsk": "Shakhtar",
};

export function displayTeamName(team: string, league?: string): string {
  if (league === "Japan League One") {
    return JL_SHORT_NAMES[team] || team;
  }
  if (SHORT_NAMES[team]) return SHORT_NAMES[team];
  if (league === "NCAAB") {
    const words = team.trim().split(" ");
    if (words.length >= 2) return words[words.length - 1];
  }
  return team;
}

export function compactTeamName(team: string, league?: string): string {
  if (league === "Japan League One") {
    return JL_SHORT_NAMES[team] || team;
  }
  if (COMPACT_NAMES[team]) return COMPACT_NAMES[team];
  if (SHORT_NAMES[team]) return SHORT_NAMES[team];
  if (league === "NCAAB") {
    const words = team.trim().split(" ");
    if (words.length >= 2) return words[words.length - 1];
  }
  // Fallback: for long unmapped names, return just the last word (the nickname)
  if (team.length > 12) {
    const words = team.trim().split(" ");
    if (words.length > 1) return words[words.length - 1];
  }
  return team;
}
